name: Run wechat token update

on:
  schedule:
    - cron: "0 */2 * * *"  # 每隔2小时运行一次

permissions:
  contents: write 

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 虚拟机

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 拉取仓库代码
        with:
          ref: ${{ github.ref }}  # 指定要拉取的分支名
          submodules: recursive       # 初始化并更新子模块
          fetch-depth: 0  
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: false

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"  # 配置用户名
          git config user.email "github-actions[bot]@users.noreply.github.com"  # 配置邮箱

           # 针对子模块的用户名和邮箱进行配置
          git submodule foreach --recursive 'git config user.name "github-actions[bot]"'
          git submodule foreach --recursive 'git config user.email "github-actions[bot]@users.noreply.github.com"'


      - name: Ensure submodules are on the correct branch
        run: |
          # 切换每个子模块到指定分支
          git submodule foreach --recursive 'branch="develop"; \
            git checkout $branch || git checkout -b $branch; \
            git pull origin $branch'


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 选择需要的 Python 版本

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 如果需要依赖，可以在项目中包含 requirements.txt
        continue-on-error: true  # 如果没有 requirements.txt 文件，则跳过

      - name: Run Python script
        run: |
          python wechat_token_trigger.py